version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.13.3
    - 2.13.4
    - 2.14.0
    - 2.14.1
    - 2.14.3
    - 3.0.1
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: gatsby-plugin-image
    versions:
    - 1.0.1
    - 1.1.0
    - 1.1.1
    - 1.1.2
    - 1.2.0
    - 1.2.1
    - 1.3.0
    - 1.3.1
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.1
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.7
    - 2.32.8
    - 2.32.9
    - 3.0.2
    - 3.0.4
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: gatsby-source-datocms
    versions:
    - 2.5.18
    - 2.6.10
    - 2.6.11
    - 2.6.12
    - 2.6.2
    - 2.6.5
    - 2.6.6
    - 2.6.8
  - dependency-name: gatsby-plugin-layout
    versions:
    - 2.1.0
    - 2.2.0
    - 2.3.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-styled-components
    versions:
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
    - 2.11.0
    - 2.11.1
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.11.0
    - 2.12.0
    - 2.12.1
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-image
    versions:
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: netlify-lambda
    versions:
    - 2.0.3
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
  - dependency-name: typeface-inter
    versions:
    - 3.15.1
  - dependency-name: gatsby-plugin-robots-txt
    versions:
    - 1.5.5
  - dependency-name: react-helmet
    versions:
    - 6.1.0
  - dependency-name: object-path
    versions:
    - 0.11.5
